### ISSUE TITLE
NoSuchMethodError using kotlin 1.4.30-M1

### ISSUE THREAD

**Issue by stephanenicolas** [cashapp/turbine#22]
Hi there, 

I am wondering if 0.30 will support 1.4.30-M1. I got this error related to turbine:
```
java.lang.NoSuchMethodError: 'java.lang.Object app.cash.turbine.FlowTurbineKt.test-dWUq8MI$default(kotlinx.coroutines.flow.Flow, double, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation, int, java.lang.Object)'
	at com.squareup.FooTest$not visible when XXX flag is off$1.invokeSuspend(TeamManagementAddOnCategoryTest.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.squareup.FooTest.not visible when XXX flag is off(FooTest.kt:57)```

**Comment by JakeWharton** [comment]
No. Once 1.4.30 final is out we can release a new minor version with support.

**Comment by stephanenicolas** [comment]
As a followup, the problem goes away when using a local snapshot of turbine compiled against kotlin 1.4.30.

**Comment by stephanenicolas** [comment]
@JakeWharton , 1.4.30 was just released. We would tremendously appreciate if you could release a minor version compiled against it. It is our last blocker to upgrade.

https://kotlinlang.org/releases.html#release-details
Thx in advance.
