### ISSUE TITLE
Testing a MutableStateFlow multiple events in order.

### ISSUE THREAD

**Issue by nilsi** [cashapp/turbine#27]
Hi,

I got some problem testing my MutableStateFlow.

Heres my code:
```
  @Test
  fun `deliver should be possible`() = runBlockingTest {
    whenever(repo.validateAddress(any())) doReturn flowOf(Either.Right(addressDeliverable))
    val viewModel = CurrentAddressViewModel(repo)

    //Passes
    flowOf("one", "two").onEach { println(it) }.test {
      assertEquals("one", expectItem())
      assertEquals("two", expectItem())
      expectComplete()
    }

    //Assertion failed
    viewModel.uiState.onEach { println(it) }.test {
      viewModel.validateAddress(addressDeliverable)

      assert(viewModel.getState().value is CurrentAddressUiState.Empty)
      assert(viewModel.getState().value is CurrentAddressUiState.Loading)
      assert(viewModel.getState().value is CurrentAddressUiState.SuccessDeliverPossible)
      expectComplete()
    }
  }
```

This is the top of the logs:
```

one
two
se.mat.matse.trx.ui.address.status.CurrentAddressUiState$Empty@649f2009
se.mat.matse.trx.ui.address.status.CurrentAddressUiState$Loading@5bbc9f97
SuccessDeliverPossible(address=Address(streetNumber=, street=, city=, postalCode=, letter=, deliverable=true))

java.lang.AssertionError: Assertion failed

	at se.mat.matse.model.product.CurrentAddressViewModelTest$deliver should be possible$1$4.invokeSuspend(CurrentAddressViewModelTest.kt:73)
	at se.mat.matse.model.product.CurrentAddressViewModelTest$deliver should be possible$1$4.invoke(CurrentAddressViewModelTest.kt)
	at app.cash.turbine.FlowTurbineKt$test$2.invokeSuspend(FlowTurbine.kt:88)
	at app.cash.turbine.FlowTurbineKt$test$2.invoke(FlowTurbine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
	at app.cash.turbine.FlowTurbineKt.test-9vOVOX0(FlowTurbine.kt:57)
	at app.cash.turbine.FlowTurbineKt.test-9vOVOX0$default(FlowTurbine.kt:54)
	at se.mat.matse.model.product.CurrentAddressViewModelTest$deliver should be possible$1.invokeSuspend(CurrentAddressViewModelTest.kt:70)
	at se.mat.matse.model.product.CurrentAddressViewModelTest$deliver should be possible$1.invoke(CurrentAddressViewModelTest.kt)
```

I want to test that it gets the following events in that order Empty, Loading, SuccessDeliverPossible.

If I remove the first two checks and then cancel the rest it works:
```
    //Assertion now passes
    viewModel.uiState.onEach { println(it) }.test {
      viewModel.validateAddress(addressDeliverable)
      assert(viewModel.getState().value is CurrentAddressUiState.SuccessDeliverPossible)
      cancelAndConsumeRemainingEvents()
    }
```

Can I use MutableStateFlow this way? 

This is the uiState defined in the viewmodel
`val uiState = MutableStateFlow<CurrentAddressUiState>(Empty)`

Thank you!

**Comment by nilsi** [comment]
I now realize that I cant do like I tried and need to use expectItem() for every event I want to check.

      assert(expectItem() is CurrentAddressUiState.Empty)
      assert(expectItem() is CurrentAddressUiState.Loading)
      assert(expectItem() is CurrentAddressUiState.SuccessDeliverPossible)

**Comment by oth-libs** [comment]
is expectMostRecentItem the replacement? it doesn't work like expected
