### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(long, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation)'

### ISSUE THREAD

**Issue by hlinero** [cashapp/turbine#68]
I have created this test, which is a copy/paste from a test in your documentation:

```kotlin
@ExperimentalCoroutinesApi
@ExperimentalTime
@Test
fun `my test`() = runBlockingTest {
    val mutableSharedFlow = MutableSharedFlow<Int>(replay = 0)
    mutableSharedFlow.test {
        mutableSharedFlow.emit(1)
        assertEquals(actual = awaitItem(), expected = 1)
        cancelAndConsumeRemainingEvents()
    }
}
```

However, when I run it, I keep getting the following error:

```kotlin
'java.lang.Object kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(long, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation)'
java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(long, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation)'
	at app.cash.turbine.ChannelBasedFlowTurbine.withTimeout(FlowTurbine.kt:228)
	at app.cash.turbine.ChannelBasedFlowTurbine.awaitEvent(FlowTurbine.kt:260)
	at app.cash.turbine.ChannelBasedFlowTurbine.awaitItem(FlowTurbine.kt:266)
	at SettingsDialogViewModelTest$my test$1$1.invokeSuspend(SettingsDialogViewModelTest.kt:25)
	at SettingsDialogViewModelTest$my test$1$1.invoke(SettingsDialogViewModelTest.kt)
	at SettingsDialogViewModelTest$my test$1$1.invoke(SettingsDialogViewModelTest.kt)
	at app.cash.turbine.FlowTurbineKt$test$2.invokeSuspend(FlowTurbine.kt:86)
	at app.cash.turbine.FlowTurbineKt$test$2.invoke(FlowTurbine.kt)
	at app.cash.turbine.FlowTurbineKt$test$2.invoke(FlowTurbine.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
	at app.cash.turbine.FlowTurbineKt.test-dWUq8MI(FlowTurbine.kt:55)
	at app.cash.turbine.FlowTurbineKt.test-dWUq8MI$default(FlowTurbine.kt:51)
	at SettingsDialogViewModelTest$my test$1.invokeSuspend(SettingsDialogViewModelTest.kt:23)
	at SettingsDialogViewModelTest$my test$1.invoke(SettingsDialogViewModelTest.kt)
	at SettingsDialogViewModelTest$my test$1.invoke(SettingsDialogViewModelTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
	(Coroutine boundary)
	at SettingsDialogViewModelTest$my test$1.invokeSuspend(SettingsDialogViewModelTest.kt:23)
	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
```

My dependencies include 

```gradle
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.5.2")
testImplementation("app.cash.turbine:turbine:0.6.1")
testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.2")
```

I am confident the test is fine since it is a copy/paste from your documentation. Not sure if I am missing any dependency or some other configuration. I would appreciate some guidance.

Not sure if the following information is relevant to better understand the problem but the project I am working is not an Android app. It is a plugin for the IntelliJ IDE written in Kotlin and it has some Swing too.

Thank you

**Comment by JakeWharton** [comment]
This is caused by a version mismatch. Despite having the correct dependency versions, something is causing the coroutine library version to be different at (test) runtime. You can use `./gradlew dependencies` to try and narrow it down.

However, I'm just going to side-step this entire class of problem and remove the usage of the experimental time APIs and release a new version.
